import { Outfit, Ovo } from 'next/font/google'
import './globals.css'

const outfit = Outfit({
  variable: '--font-geist-sans',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

const ovo = Ovo({
  variable: '--font-geist-mono',
  subsets: ['latin'],
  weight: ['400'],
})

export const metadata = {
  title: 'General VA | - Mark Ivan Dela Vega',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' className='scroll-smooth'>
      <body
        className={`${outfit.variable} ${ovo.variable} antialiased leading-8 overflow-x-hidden dark:bg-darkTheme dark:text-white`}
      >
        {children}
      </body>
    </html>
  )
}
